export {
  COMMENT_APPENDIX_DIRECTIVE_NAME,
  appendThreadComment,
  countResolvedCommentThreads,
  createCommentAnchorFromContainer,
  createCommentQuoteFromContainer,
  createComment,
  createCommentThread,
  deleteThreadComment,
  deleteCommentThread,
  editThreadComment,
  getCommentThreadUpdatedAt,
  haveSameCommentThreads,
  isResolvedCommentThread,
  listCommentTargetContainers,
  parseCommentAppendixPayload,
  repairCommentThread,
  serializeCommentAppendixPayload,
  updateCommentThreadStatus,
} from "./anchors";
export type {
  Comment,
  CommentAnchor,
  CommentAnchorMatch,
  CommentAppendixPayload,
  CommentRepairMatchStrategy,
  CommentRepairResult,
  CommentTargetContainer,
  CommentThread,
} from "./types";
